name: publish

on:
    workflow_dispatch:
    pull_request:
    push:
        branches:
            - main
    release:
        types:
            - published

env:
    FORCE_COLOR: 3

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Install uv
              uses: astral-sh/setup-uv@v3

            - name: Build
              run: uv build

            - name: Check metadata
              run: uvx twine check dist/*

            - uses: actions/upload-artifact@v4
              with:
                  name: builds
                  path: dist/*

    upload_all:
        name: Upload if release
        needs: [build]
        runs-on: ubuntu-latest
        if: github.event_name == 'release' && github.event.action == 'published'
        environment: pypi
        permissions:
            id-token: write

        steps:
            - uses: actions/setup-python@v5
              with:
                  python-version: "3.x"

            - uses: actions/download-artifact@v4
              with:
                  name: builds
                  path: dist/

            - uses: pypa/gh-action-pypi-publish@release/v1
